sudo: required
service:
  - docker

before_install:
  - docker build -t tarski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tarski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "tupowinnabyćnazwabucketzaws"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"